import json
import os
import re
import uuid
from typing import Any, Dict, List

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_AUTO_SIZE, PP_ALIGN
from pptx.util import Inches, Pt

from models.schemas import DocumentReference, PPTRequest
from services.llm import get_llm


SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

COLORS = {
    "background": RGBColor(250, 248, 241),
    "card": RGBColor(255, 255, 255),
    "ink": RGBColor(43, 35, 25),
    "muted": RGBColor(112, 95, 68),
    "gold": RGBColor(181, 137, 48),
    "gold_soft": RGBColor(244, 230, 187),
    "line": RGBColor(222, 203, 157),
    "green": RGBColor(65, 128, 104),
}


def _safe_text(value: Any, fallback: str = "") -> str:
    if value is None:
        return fallback
    return str(value).strip() or fallback


def _clean_json(content: str) -> str:
    content = content.strip()
    if content.startswith("```json"):
        return content[7:-3].strip()
    if content.startswith("```"):
        return content[3:-3].strip()
    return content


def _shorten(value: str, max_chars: int) -> str:
    value = _safe_text(value)
    return value if len(value) <= max_chars else value[: max_chars - 1].rstrip() + "..."


def _one_line(value: str, max_chars: int) -> str:
    return _shorten(re.sub(r"\s+", " ", _safe_text(value)), max_chars)


def _compact_bullets(values: List[Any], max_items: int = 4, max_chars: int = 95) -> List[str]:
    bullets = []
    for value in values:
        text = _one_line(value, max_chars)
        if text:
            bullets.append(text)
        if len(bullets) >= max_items:
            break
    return bullets


def _reference_payload(references: List[DocumentReference]) -> List[Dict[str, Any]]:
    payload = []
    for idx, ref in enumerate(references, start=1):
        meta = ref.metadata or {}
        payload.append(
            {
                "doc_id": f"Doc {idx}",
                "file_name": ref.file_name,
                "summary": ref.summary,
                "client": meta.get("client_name") or meta.get("client_project") or "N/A",
                "poc": meta.get("pocs") or meta.get("created_by") or "Unknown",
                "objective": meta.get("business_objective") or "",
                "approach": meta.get("approach") or "",
                "datasets": meta.get("datasets_used") or "",
                "outcome": meta.get("key_outcome") or "",
                "topic": meta.get("topic") or "",
            }
        )
    return payload


def _fallback_deck_plan(request: PPTRequest) -> Dict[str, Any]:
    references = _reference_payload(request.references)
    summary_points = [
        line.strip(" -*")
        for line in re.split(r"\n+", request.content)
        if line.strip() and not line.strip().startswith("**")
    ][:4]
    if not summary_points:
        summary_points = ["BLITZ synthesized the current RAG response into a client-ready enablement narrative."]

    return {
        "deck_title": request.topic,
        "subtitle": "Generated by BLITZ Enterprise Intelligence",
        "executive_summary": summary_points[:3],
        "business_context": request.user_query or request.topic,
        "recommended_approach": [
            "Clarify the client objective and decision context.",
            "Map relevant prior work, datasets, and subject matter expertise.",
            "Shape the response into a proposal-ready storyline with cited evidence.",
        ],
        "relevant_experience": [
            {
                "headline": ref["file_name"],
                "detail": ref["summary"],
                "source": ref["doc_id"],
                "poc": ref["poc"],
            }
            for ref in references[:4]
        ],
        "next_steps": [
            "Validate source fit with the listed POCs.",
            "Confirm scope, data availability, and deliverable expectations.",
            "Convert the recommended approach into a client-facing proposal deck.",
        ],
        "evidence": references,
    }


def _generate_deck_plan(request: PPTRequest) -> Dict[str, Any]:
    references = _reference_payload(request.references)
    llm = get_llm()
    prompt = f"""You are BLITZ Deck Architect, a consulting presentation strategist.
Create a polished, executive-ready deck plan from the RAG answer and retrieved source metadata.

Return ONLY valid JSON with this exact top-level shape:
{{
  "deck_title": "short title",
  "subtitle": "short subtitle",
  "executive_summary": ["3 concise board-level points"],
  "business_context": "1 paragraph explaining the client need or question",
  "recommended_approach": ["4 to 5 concise steps"],
  "relevant_experience": [
    {{"headline": "source-backed capability", "detail": "specific evidence", "source": "Doc 1", "poc": "name"}}
  ],
  "next_steps": ["3 pragmatic next steps"],
  "evidence": [
    {{"doc_id": "Doc 1", "file_name": "filename", "client": "client", "poc": "POC", "summary": "why it matters"}}
  ]
}}

Rules:
- Use the references as the evidence base; do not invent source files or POCs.
- Write like a Chryselys consulting deliverable, not a chatbot transcript.
- Keep slide text compact. No bullet should exceed 16 words.
- Keep titles under 8 words and details under 22 words.
- Make recommended_approach actionable.

Topic: {request.topic}
Original user question: {request.user_query or "N/A"}

RAG answer:
{request.content[:5000]}

Retrieved references:
{json.dumps(references, indent=2)[:5000]}
"""

    try:
        raw = llm.invoke(prompt).content
        plan = json.loads(_clean_json(raw))
        if isinstance(plan, dict) and plan.get("deck_title"):
            if not plan.get("evidence"):
                plan["evidence"] = references
            return plan
    except Exception as e:
        print(f"Deck planning failed, using fallback: {e}")

    return _fallback_deck_plan(request)


def _set_background(slide, color=COLORS["background"]):
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, SLIDE_H)
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()


def _add_text(slide, text, x, y, w, h, size=18, color=None, bold=False, align=None):
    box = slide.shapes.add_textbox(x, y, w, h)
    frame = box.text_frame
    frame.clear()
    frame.word_wrap = True
    frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
    frame.margin_left = Inches(0.02)
    frame.margin_right = Inches(0.02)
    frame.margin_top = Inches(0.01)
    frame.margin_bottom = Inches(0.01)
    p = frame.paragraphs[0]
    p.text = _safe_text(text)
    if align:
        p.alignment = align
    run = p.runs[0] if p.runs else p.add_run()
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.name = "Aptos"
    run.font.color.rgb = color or COLORS["ink"]
    return box


def _add_bullets(slide, bullets, x, y, w, h, size=15, color=None):
    box = slide.shapes.add_textbox(x, y, w, h)
    frame = box.text_frame
    frame.clear()
    frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
    frame.margin_left = Inches(0.02)
    frame.margin_right = Inches(0.05)
    frame.margin_top = Inches(0.02)
    frame.margin_bottom = Inches(0.02)
    frame.word_wrap = True
    for idx, bullet in enumerate(_compact_bullets(bullets, max_items=5, max_chars=105)):
        p = frame.paragraphs[0] if idx == 0 else frame.add_paragraph()
        p.text = f"- {_one_line(bullet, 105)}"
        p.level = 0
        p.space_after = Pt(5)
        p.font.size = Pt(size)
        p.font.name = "Aptos"
        p.font.color.rgb = color or COLORS["ink"]
    return box


def _add_header(slide, title: str, kicker: str):
    _add_text(slide, kicker.upper(), Inches(0.65), Inches(0.34), Inches(5.5), Inches(0.25), 8, COLORS["gold"], True)
    _add_text(slide, title, Inches(0.65), Inches(0.62), Inches(8.4), Inches(0.62), 24, COLORS["ink"], True)
    line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.65), Inches(1.32), Inches(12.0), Inches(0.01))
    line.fill.solid()
    line.fill.fore_color.rgb = COLORS["line"]
    line.line.fill.background()


def _add_footer(slide, page: int):
    _add_text(slide, "BLITZ Enterprise Intelligence | Generated from cited RAG synthesis", Inches(0.65), Inches(7.08), Inches(7.0), Inches(0.2), 7, COLORS["muted"])
    _add_text(slide, str(page).zfill(2), Inches(12.25), Inches(7.05), Inches(0.45), Inches(0.22), 8, COLORS["gold"], True, PP_ALIGN.RIGHT)


def _add_card(slide, x, y, w, h, title, body, badge=None):
    card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, x, y, w, h)
    card.fill.solid()
    card.fill.fore_color.rgb = COLORS["card"]
    card.line.color.rgb = COLORS["line"]
    _add_text(slide, _one_line(title, 58), x + Inches(0.22), y + Inches(0.16), w - Inches(1.25 if badge else 0.44), Inches(0.34), 12, COLORS["ink"], True)
    _add_text(slide, _one_line(body, 210), x + Inches(0.22), y + Inches(0.62), w - Inches(0.44), h - Inches(0.82), 8, COLORS["muted"])
    if badge:
        _add_text(slide, badge, x + w - Inches(1.15), y + Inches(0.18), Inches(0.9), Inches(0.22), 8, COLORS["gold"], True, PP_ALIGN.RIGHT)


def _slide_title(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_text(slide, "BLITZ", Inches(0.72), Inches(0.45), Inches(1.7), Inches(0.3), 14, COLORS["gold"], True)
    _add_text(slide, _one_line(plan.get("deck_title", "Client Enablement Deck"), 72), Inches(0.72), Inches(1.75), Inches(8.6), Inches(1.2), 34, COLORS["ink"], True)
    _add_text(slide, _one_line(plan.get("subtitle", "Generated by BLITZ Enterprise Intelligence"), 90), Inches(0.78), Inches(3.08), Inches(6.6), Inches(0.5), 15, COLORS["muted"])
    _add_bullets(slide, plan.get("executive_summary", [])[:3], Inches(0.85), Inches(4.18), Inches(5.9), Inches(1.45), 13)
    orb = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(8.35), Inches(1.3), Inches(3.6), Inches(3.6))
    orb.fill.solid()
    orb.fill.fore_color.rgb = COLORS["gold_soft"]
    orb.line.color.rgb = COLORS["line"]
    _add_text(slide, "RAG", Inches(9.25), Inches(2.35), Inches(1.8), Inches(0.6), 32, COLORS["gold"], True, PP_ALIGN.CENTER)
    _add_text(slide, "Cited synthesis\nSource mapping\nProposal-ready", Inches(8.9), Inches(3.1), Inches(2.45), Inches(0.8), 12, COLORS["muted"], False, PP_ALIGN.CENTER)
    _add_footer(slide, 1)


def _slide_summary(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Executive Summary", "Decision Brief")
    _add_bullets(slide, plan.get("executive_summary", []), Inches(0.9), Inches(1.75), Inches(5.75), Inches(2.45), 16)
    _add_card(slide, Inches(7.05), Inches(1.75), Inches(4.95), Inches(2.05), "Business context", _one_line(plan.get("business_context", ""), 255))
    _add_card(slide, Inches(7.15), Inches(4.15), Inches(4.8), Inches(1.55), "Recommended posture", "Use prior Chryselys evidence to shape a focused client conversation and accelerate proposal development.")
    _add_footer(slide, 2)


def _slide_experience(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Relevant Chryselys Experience", "Evidence-backed capabilities")
    items = plan.get("relevant_experience", [])[:3]
    positions = [(0.8, 1.72), (4.75, 1.72), (8.7, 1.72)]
    for idx, item in enumerate(items):
        x, y = positions[idx]
        badge = item.get("source") or f"Doc {idx + 1}"
        body = f"{_one_line(item.get('detail', ''), 150)} | POC: {_one_line(item.get('poc', 'Unknown'), 28)}"
        _add_card(slide, Inches(x), Inches(y), Inches(3.45), Inches(3.95), item.get("headline", "Relevant asset"), body, badge)
    _add_text(
        slide,
        "Each experience card is source-backed and intended as a prompt for proposal narrative, SME follow-up, and client-facing proof points.",
        Inches(1.0),
        Inches(6.0),
        Inches(11.0),
        Inches(0.36),
        11,
        COLORS["muted"],
        False,
        PP_ALIGN.CENTER,
    )
    _add_footer(slide, 3)


def _slide_approach(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Recommended Approach", "Execution storyline")
    steps = _compact_bullets(plan.get("recommended_approach", []), max_items=5, max_chars=72)
    left = Inches(0.95)
    top = Inches(2.0)
    gap = Inches(2.25)
    for idx, step in enumerate(steps):
        x = left + Inches(idx * 2.35)
        circle = slide.shapes.add_shape(MSO_SHAPE.OVAL, x, top, Inches(0.58), Inches(0.58))
        circle.fill.solid()
        circle.fill.fore_color.rgb = COLORS["gold"]
        circle.line.fill.background()
        _add_text(slide, str(idx + 1), x + Inches(0.16), top + Inches(0.09), Inches(0.25), Inches(0.24), 12, RGBColor(255, 255, 255), True, PP_ALIGN.CENTER)
        if idx < len(steps) - 1:
            line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, x + Inches(0.68), top + Inches(0.28), gap - Inches(0.15), Inches(0.025))
            line.fill.solid()
            line.fill.fore_color.rgb = COLORS["line"]
            line.line.fill.background()
        _add_text(slide, step, x - Inches(0.18), top + Inches(0.86), Inches(1.88), Inches(1.02), 10, COLORS["ink"], True, PP_ALIGN.CENTER)
    _add_footer(slide, 4)


def _slide_evidence(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Evidence & Source Mapping", "RAG provenance")
    evidence = plan.get("evidence", [])[:5]
    _add_text(slide, "ID", Inches(0.85), Inches(1.48), Inches(0.55), Inches(0.18), 7, COLORS["gold"], True)
    _add_text(slide, "Source", Inches(1.55), Inches(1.48), Inches(3.9), Inches(0.18), 7, COLORS["gold"], True)
    _add_text(slide, "Client", Inches(5.55), Inches(1.48), Inches(1.4), Inches(0.18), 7, COLORS["gold"], True)
    _add_text(slide, "POC", Inches(6.95), Inches(1.48), Inches(1.45), Inches(0.18), 7, COLORS["gold"], True)
    _add_text(slide, "Why it matters", Inches(8.45), Inches(1.48), Inches(3.75), Inches(0.18), 7, COLORS["gold"], True)
    y = Inches(1.78)
    for idx, item in enumerate(evidence):
        row_y = y + Inches(idx * 0.82)
        _add_text(slide, item.get("doc_id", f"Doc {idx + 1}"), Inches(0.85), row_y, Inches(0.65), Inches(0.24), 8, COLORS["gold"], True)
        _add_text(slide, _one_line(item.get("file_name", "Source document"), 52), Inches(1.55), row_y, Inches(3.75), Inches(0.3), 8, COLORS["ink"], True)
        _add_text(slide, _one_line(item.get("client", "N/A"), 22), Inches(5.55), row_y, Inches(1.25), Inches(0.3), 7, COLORS["muted"])
        _add_text(slide, _one_line(item.get("poc", "Unknown"), 24), Inches(6.95), row_y, Inches(1.3), Inches(0.3), 7, COLORS["muted"])
        _add_text(slide, _one_line(item.get("summary", ""), 88), Inches(8.45), row_y, Inches(3.75), Inches(0.38), 7, COLORS["muted"])
        line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.85), row_y + Inches(0.5), Inches(11.35), Inches(0.01))
        line.fill.solid()
        line.fill.fore_color.rgb = COLORS["line"]
        line.line.fill.background()
    _add_footer(slide, 5)


def _slide_next_steps(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Suggested Next Steps", "Path to client-ready action")
    _add_bullets(slide, plan.get("next_steps", []), Inches(0.95), Inches(1.8), Inches(5.7), Inches(2.3), 16)
    _add_card(slide, Inches(7.2), Inches(1.85), Inches(4.7), Inches(2.5), "BLITZ output advantage", "This deck combines the RAG answer, source provenance, and recommended proposal motion into one reusable enablement artifact.")
    _add_footer(slide, 6)


def _slide_appendix(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)
    _add_header(slide, "Appendix: Referenced Documents", "Full source list")
    evidence = plan.get("evidence", [])
    bullets = [
        f"{item.get('doc_id', f'Doc {idx + 1}')}: {_one_line(item.get('file_name', 'Source'), 58)} | Client: {_one_line(item.get('client', 'N/A'), 24)} | POC: {_one_line(item.get('poc', 'Unknown'), 24)}"
        for idx, item in enumerate(evidence[:8])
    ] or ["No source references were provided with this deck request."]
    _add_bullets(slide, bullets, Inches(0.9), Inches(1.65), Inches(11.3), Inches(4.8), 10)
    _add_footer(slide, 7)


def build_ppt(request: PPTRequest) -> str:
    plan = _generate_deck_plan(request)
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    _slide_title(prs, plan)
    _slide_summary(prs, plan)
    _slide_experience(prs, plan)
    _slide_approach(prs, plan)
    _slide_evidence(prs, plan)
    _slide_next_steps(prs, plan)
    _slide_appendix(prs, plan)

    os.makedirs("exports", exist_ok=True)
    safe_topic = re.sub(r"[^a-zA-Z0-9_-]+", "_", request.topic).strip("_")[:36] or "blitz_deck"
    file_path = os.path.join("exports", f"{safe_topic}_{uuid.uuid4().hex[:8]}.pptx")
    prs.save(file_path)
    return file_path
