import os
from fastapi import APIRouter
from fastapi.responses import FileResponse
from pydantic import BaseModel
from pptx import Presentation
from services.llm import get_llm

router = APIRouter()

class PPTRequest(BaseModel):
    topic: str
    content: str # The synthesized AI answer to convert to slides

@router.post("/")
async def generate_ppt(request: PPTRequest):
    """Generates a PPT based on the provided content."""
    llm = get_llm()
    
    # Ask LLM to break content into slide points
    prompt = f"""Convert the following content into exactly 3 slide points for a presentation on '{request.topic}'. 
Format strictly as:
Slide 1: [Title] - [Bullet points]
Slide 2: [Title] - [Bullet points]
Slide 3: [Title] - [Bullet points]

Content: {request.content}"""
    
    res = llm.invoke(prompt).content
    
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = request.topic
    slide.placeholders[1].text = "Generated by AI Knowledge Engine"
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    slides_data = res.split("Slide ")[1:] 
    for slide_data in slides_data:
        try:
            parts = slide_data.split(":", 1)
            if len(parts) > 1:
                content_parts = parts[1].split("-", 1)
                slide_title = content_parts[0].strip()
                slide_bullets = content_parts[1].strip() if len(content_parts) > 1 else ""
                
                slide = prs.slides.add_slide(bullet_slide_layout)
                slide.shapes.title.text = slide_title
                slide.placeholders[1].text = slide_bullets
        except Exception as e:
            print(f"Error parsing slide: {e}")
            
    os.makedirs("exports", exist_ok=True)
    file_path = f"exports/{request.topic.replace(' ', '_')[:20]}.pptx"
    prs.save(file_path)
    
    return FileResponse(
        path=file_path, 
        filename=f"{request.topic[:20]}.pptx", 
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
    )
